import './globals.css'
import Navigation from './components/Navigation'
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Next 13 js App</title>
      </head>
      <body>
        <header>
          <Navigation />
        </header>
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  )
}
